export const geoJSONProp = {
  type: {
    type: String,
    name: String,
    crs: {
      type: String,
      properties: {
        name: String,
      },
    },
    features: {
      type: String,
      properties: {
        ID_0: Number,
        ISO: String,
        NAME_0: String,
        OBJECTID_1: Number,
        ISO3: String,
        NAME_ENGLI: String,
        NAME_ISO: String,
        NAME_FAO: String,
        NAME_LOCAL: String,
        NAME_OBSON: String,
        NAME_VARIA: String,
        NAME_NONLN: String,
        NAME_FRENC: String,
        NAME_SPANI: String,
        NAME_RUSSI: String,
        NAME_ARABI: String,
        NAME_CHINE: String,
        WASPARTON: String,
        CONTAINN: String,
        SOVEREIGN: String,
        ISO2: String,
        WWN: String,
        FIPS: String,
        ISON: Number,
        VALIDFR: String,
        VALIDTO: String,
        POP2000: Number,
        SQKM: Number,
        POPSQKM: Number,
        UNREGION1: String,
        UNREGION2: String,
        DEVELOPING: Number,
        CIS: Number,
        Transition: Number,
        OECD: Number,
        WBREGION: String,
        WBINCOME: String,
        WBDEBT: String,
        WBOTHEN: String,
        CEEAC: Number,
        CEMAC: Number,
        CEPLG: Number,
        COMESA: Number,
        EAC: Number,
        ECOWAS: Number,
        IGAD: Number,
        IOC: Number,
        MRU: Number,
        SACU: Number,
        UEMOA: Number,
        UMA: Number,
        PALOP: Number,
        PARTA: Number,
        CACM: Number,
        EurAsEC: Number,
        Agadir: Number,
        SAARC: Number,
        ASEAN: Number,
        NAFTA: Number,
        GCC: Number,
        CSN: Number,
        CARICOM: Number,
        EU: Number,
        CAN: Number,
        ACP: Number,
        Landlocked: Number,
        AOSIS: Number,
        SIDS: Number,
        Islands: Number,
        LDC: Number,
      },
      geometry: { type: String, coordinates: [[[[Number]]]] },
    },
  },
};
